export const quiz_one = {
  quizTitle: "Тест по JavaScript",
  nrOfQuestions: "7",
  questions: [
    {
      question: "Что Представляет собой Event Loop",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Ассинхронность", "Онднопоточночность", "Web API"],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Обьекты это тип?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Ссылочный", "По значению", "Прототип"],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Typeof Null",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["undefined", "Null", "Object"],
      correctAnswer: "3",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Что такое DOM?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Data Driven Document",
        "Document Object Model",
        "Document Operator Machine",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Что это за оператор '...'?",
      questionType: "text",
      answerSelectionType: "multiple",
      answers: [
        "rest",
        "spead",
        "destructure",
        "замыкание",
        "погружение",
        "цикл",
        "ключ",
      ],
      correctAnswer: [1, 2, 3],
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Когда вышел стандарт ES5?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["2009", "2015", "2013"],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Кто создал JS?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Крис Бирд", "Стив Возняк", "Брендан Эйх"],
      correctAnswer: "3",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
  ],
};

export const quiz_second = {
  quizTitle: "Тест по Html",
  nrOfQuestions: "5",
  questions: [
    {
      question: "Что такое HTML?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Язык разметки", "Язык программирования", "Сайт"],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "<P></P> это элемент? ",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Строчный", "Блочный", "Строчно-блочный"],
      correctAnswer: "2",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "что такое Doctype?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["тип документа", "тип страницы", " тип тега"],
      correctAnswer: "3",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Что такое DOM?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Data Driven Document",
        "Document Object Model",
        "Document Operator Machine",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "как сделать ссылку?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "<a></a>",
        "<b></b>",
        "<p></p>",
        "<i></i>",
        "<div></div>",
        "<code></code>",
        "<link></link>",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
 
 
  ],
};


export const quiz_third = {
  quizTitle: "Тест по CSS",
  nrOfQuestions: "5",
  questions: [
    {
      question: "Что такое CSS?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Стили", "Каскадные стили", "Таблица Стилей"],
      correctAnswer: "3",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "Что такое специфичность селекторов CSS? ",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Вес", "Приоритет", "Стиль"],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "что такое normalize.css?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["сброс стилей", "нормализация", " подтверждение стилей"],
      correctAnswer: "2",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question:
        " Как работать со стилями в старых браузерах с ограниченными возможностями? Какие методы/техники вы используете ? ",
      questionType: "text",
      answerSelectionType: "multiply",
      answers: ["HTML", "CSS", "CSS3", "style", "vanila","JavaScript"],
      correctAnswer: ["1","2","3","6"],
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
    {
      question: "что реализует :hover?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "эфект при наведении",
        "затемнение",
        "скрытие",
        "стили под ночнную тему",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: " Правильно",
      messageForIncorrectAnswer: "Неправильно",
      point: "20",
    },
  ],
};